"""Add inspections table

Revision ID: 003_add_inspections
Revises: 002_add_inspectors
Create Date: 2025-10-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003_add_inspections'
down_revision = '002_add_inspectors'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create vehicle type enum
    op.execute("CREATE TYPE vehicletype AS ENUM ('car', 'motorcycle')")

    # Create inspection status enum
    op.execute("CREATE TYPE inspectionstatus AS ENUM ('draft', 'completed')")

    # Create inspections table
    op.create_table('inspections',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('license_plate', sa.String(length=20), nullable=False),
        sa.Column('vehicle_type', sa.Enum('car', 'motorcycle', name='vehicletype'), nullable=False),
        sa.Column('inspector_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('checkpoint_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('is_safe', sa.Boolean(), nullable=True),
        sa.Column('requires_reinspection', sa.Boolean(), nullable=True),
        sa.Column('observations', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('draft', 'completed', name='inspectionstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['inspector_id'], ['inspectors.id'], name='fk_inspections_inspector_id')
    )

    # Create indexes for performance
    op.create_index(op.f('ix_inspections_license_plate'), 'inspections', ['license_plate'], unique=False)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_license_plate'), table_name='inspections')

    # Drop table
    op.drop_table('inspections')

    # Drop enum types
    op.execute("DROP TYPE inspectionstatus")
    op.execute("DROP TYPE vehicletype")

    # ### end Alembic commands ###
